### ISSUE TITLE
Bilder in zweispaltiger Zeile wird klein dargestellt

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/Newsletter#34]
![bildschirmfoto 2015-10-06 um 23 36 45](https://cloud.githubusercontent.com/assets/11321756/10323431/4b833bd8-6c83-11e5-9b4a-db143648355a.png)

**Comment by cowboyxup** [comment]
@larsboehnke kann den fehler nicht reproduzieren (firefox/chrome auf win10)

**Comment by larsboehnke** [comment]
@thomas-nds und ich sind auf OS X, Safari, Firefox und Chrome, @cowboyxup.

**Comment by cowboyxup** [comment]
@larsboehnke Konnte den Fehler reproduzieren. Es ist allerdings kein Fehler des Templates sondern eine Fehlbedienung von Mailchimp. Wenn bei einem Bild unter Settings eine Breite gesetzt ist, bzw. mal gesetzt war, dann wird das bild natürlich verkleinert. Dies passiert auch, wenn das bei dem vorherigen Content Block war und dann ein neuer erstellt wird. Antscheinend wird das dann kopiert. Ich vermute mal die Breite des Bildes beträgt 281px, wie in #42

**Comment by larsboehnke** [comment]
@cowboyxup, ok dann schleiße ich das Ticket. Sollte der Fehler wieder auftreten und es liegt nicht daran, eröffne ich es wieder.

**Comment by cowboyxup** [comment]
Fehler gefunden
