### ISSUE TITLE
Inkompatible CSS-Angaben überprüfen

### ISSUE THREAD

**Issue by 0711master** [pfadfinden/Newsletter#39]
Manche Clients unterstützen manche CSS-Angaben nicht: https://www.campaignmonitor.com/css/

**Comment by cowboyxup** [comment]
Dass manche Clients maches nicht unterstützen ist klar. Auf Grund dessen sind einige Angaben doppelt vorhanden oder es wird nicht optimal angezeigt. Dass ist einfach so und solange die Hersteller der Clients sich nicht einigen, ist dass einfach so. Wir versuchen das Design so gut wie möglich umzusetzten, aber müssen mit Einschränkungen leben. Es öfteren muss zwischen den Darstellungen verschiednener Clients abgewägt werden, was schlimmer ist. 
@0711master Sollte der Newsletter auf einem Client nicht gut aussehen und dieser Fehler ist auch nicht in der Redme dokumentiert sein, dann kannst du gerne ein Ticket mit Screenshot und Clientversion/Betriebssystem etc. eröffnen
