### ISSUE TITLE
Angepasste Version für Bundesverband ohne Regionalleiste

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/Newsletter#45]
Da die Bundesmail auch auf das neue Design umgestellt wird, brauchen wir entweder ein Codesnippet zum drüber passen oder einen neuen Branch mit einer angepassten Version für den Bund.

**Comment by philippst** [comment]
Die Zeile können wir sehr einfach direkt aus dem Quellcode nehmen. Da muss Christian glaube ich keinen eignen Branch aufmachen.

**Comment by larsboehnke** [comment]
@philippst dann passt die insgesamte Höhe nicht mehr und der Text zum Browser anzeigen (der zweizeilig ist) wird abgeschnitten. So hatte ich das auch erst versucht.
